name: Build with PyInstaller

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  pyinstaller-build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r RasterizeGrayScaleToPalette/requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller RasterizeGrayScaleToPalette/RasterizeGrayScaleToPalette.spec

    - name: Copy additional files
      shell: pwsh
      run: |
        $distDir = Join-Path "${{ github.workspace }}" "RasterizeGrayScaleToPalette/dist"
        New-Item -ItemType Directory -Path $distDir -Force | Out-Null

        Copy-Item -LiteralPath (Join-Path "${{ github.workspace }}" "LICENSE.txt") -Destination (Join-Path $distDir "LICENSE.txt") -Force
        Copy-Item -LiteralPath (Join-Path "${{ github.workspace }}" "README.md") -Destination (Join-Path $distDir "README.md") -Force


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: RasterizeGrayScaleToPalette-windows
        path: RasterizeGrayScaleToPalette/dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          RasterizeGrayScaleToPalette/dist/**
        generate_release_notes: true
